import asyncio
import logging
import math
import re
from typing import Any

import httpx
from fastapi import APIRouter, HTTPException, Request
from pydantic import BaseModel, ConfigDict, Field

from auth import RequireAPIKey
from client_ip import pseudonymize_lampada_client, resolve_client_ip
from config import (
    GEMINI_API_KEY,
    GEMINI_MODEL,
    GEMINI_REQUESTS_PER_CLIENT_PER_MINUTE,
    GEMINI_REQUESTS_PER_MINUTE,
    LAMPADA_SYSTEM_PROMPT,
)
from database import create_connection


router = APIRouter()
MODEL_PATTERN = re.compile(r"^[a-zA-Z0-9._-]+$")
logger = logging.getLogger(__name__)
_RATE_LIMIT_WINDOW_SECONDS = 60
_RATE_LIMIT_LOCK_NAME = "bible_api_lampada_rate_limit"


class CompleteRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    user: str = Field(
        min_length=1,
        max_length=16000,
        description="User message to answer",
    )


class CompleteResponse(BaseModel):
    text: str = Field(description="Text generated by the AI companion")


class ErrorResponse(BaseModel):
    detail: str = Field(description="Public error message")


class GeminiError(RuntimeError):
    pass


class RateLimitError(RuntimeError):
    def __init__(self, message: str, retry_after: int | None = None):
        super().__init__(message)
        self.retry_after = retry_after


def _retry_after(age_microseconds: int | None) -> int:
    age_seconds = (age_microseconds or 0) / 1_000_000
    return max(1, math.ceil(_RATE_LIMIT_WINDOW_SECONDS - age_seconds))


def _read_usage(cursor: Any, client_hash: bytes | None = None) -> tuple[int, int | None]:
    sql = """
        SELECT
            COUNT(*),
            TIMESTAMPDIFF(MICROSECOND, MIN(dt_create), UTC_TIMESTAMP(6))
        FROM lampada_rate_limit_events
        WHERE dt_create > UTC_TIMESTAMP(6) - INTERVAL 60 SECOND
    """
    params: tuple[bytes, ...] = ()
    if client_hash is not None:
        sql += " AND client_hash = %s"
        params = (client_hash,)
    cursor.execute(sql, params)
    count, oldest_age = cursor.fetchone()
    return int(count), oldest_age


def _reserve_rate_limit(client_key: str) -> None:
    connection = create_connection()
    if connection is None:
        raise RateLimitError("rate limit storage is unavailable")

    lock_acquired = False
    cursor = None
    try:
        cursor = connection.cursor()
        cursor.execute("SELECT GET_LOCK(%s, 2)", (_RATE_LIMIT_LOCK_NAME,))
        lock_acquired = cursor.fetchone()[0] == 1
        if not lock_acquired:
            raise RateLimitError("rate limit lock is unavailable")

        cursor.execute(
            """
            DELETE FROM lampada_rate_limit_events
            WHERE dt_create <= UTC_TIMESTAMP(6) - INTERVAL 60 SECOND
            """
        )

        global_count, global_age = _read_usage(cursor)
        if global_count >= GEMINI_REQUESTS_PER_MINUTE:
            raise RateLimitError(
                "global AI request limit exceeded",
                _retry_after(global_age),
            )

        try:
            client_hash = bytes.fromhex(pseudonymize_lampada_client(client_key))
        except RuntimeError as error:
            raise RateLimitError(str(error)) from error
        client_count, client_age = _read_usage(cursor, client_hash)
        if client_count >= GEMINI_REQUESTS_PER_CLIENT_PER_MINUTE:
            raise RateLimitError(
                "client AI request limit exceeded",
                _retry_after(client_age),
            )

        cursor.execute(
            """
            INSERT INTO lampada_rate_limit_events (client_hash, dt_create)
            VALUES (%s, UTC_TIMESTAMP(6))
            """,
            (client_hash,),
        )
        connection.commit()
    except RateLimitError:
        connection.rollback()
        raise
    except Exception as error:
        connection.rollback()
        raise RateLimitError("rate limit storage failed") from error
    finally:
        if cursor is not None and lock_acquired:
            try:
                cursor.execute("SELECT RELEASE_LOCK(%s)", (_RATE_LIMIT_LOCK_NAME,))
                cursor.fetchone()
            except Exception:
                logger.warning("Failed to release Lampada rate limit lock")
        if cursor is not None:
            try:
                cursor.close()
            except Exception:
                logger.warning("Failed to close Lampada rate limit cursor")
        try:
            connection.close()
        except Exception:
            logger.warning("Failed to close Lampada rate limit connection")


async def _enforce_rate_limit(client_key: str) -> None:
    try:
        await asyncio.to_thread(_reserve_rate_limit, client_key)
    except RateLimitError as error:
        if error.retry_after is not None:
            raise HTTPException(
                status_code=429,
                detail="AI request limit exceeded",
                headers={"Retry-After": str(error.retry_after)},
            ) from error
        logger.warning("Lampada rate limiter unavailable: %s", error)
        raise HTTPException(
            status_code=503,
            detail="AI service temporarily unavailable",
        ) from error


def _extract_text(data: Any) -> str:
    try:
        parts = data["candidates"][0]["content"]["parts"]
    except (KeyError, IndexError, TypeError):
        return ""
    if not isinstance(parts, list):
        return ""
    return "".join(
        part.get("text", "")
        for part in parts
        if isinstance(part, dict) and isinstance(part.get("text"), str)
    ).strip()


async def complete(user: str) -> str:
    if not GEMINI_API_KEY:
        raise GeminiError("GEMINI_API_KEY is not configured")
    if not LAMPADA_SYSTEM_PROMPT:
        raise GeminiError("LAMPADA_SYSTEM_PROMPT is not configured")
    if len(LAMPADA_SYSTEM_PROMPT) > 8000:
        raise GeminiError("LAMPADA_SYSTEM_PROMPT is too long")
    if not MODEL_PATTERN.fullmatch(GEMINI_MODEL):
        raise GeminiError("GEMINI_MODEL contains invalid characters")

    url = (
        "https://generativelanguage.googleapis.com/v1beta/models/"
        f"{GEMINI_MODEL}:generateContent"
    )
    payload = {
        "system_instruction": {"parts": [{"text": LAMPADA_SYSTEM_PROMPT}]},
        "contents": [{"role": "user", "parts": [{"text": user}]}],
        "generationConfig": {
            "maxOutputTokens": 1024,
            "temperature": 0.7,
        },
    }

    try:
        async with httpx.AsyncClient(timeout=20.0) as client:
            response = await client.post(
                url,
                headers={"x-goog-api-key": GEMINI_API_KEY},
                json=payload,
            )
            response.raise_for_status()
            data = response.json()
    except httpx.TimeoutException as error:
        raise GeminiError("Gemini request timed out") from error
    except (httpx.HTTPError, ValueError) as error:
        raise GeminiError("Gemini request failed") from error

    text = _extract_text(data)
    if not text:
        raise GeminiError("Gemini returned no text")
    return text


@router.post(
    "/lampada/v1/complete",
    response_model=CompleteResponse,
    operation_id="lampada_complete",
    tags=["Lampada"],
    summary="Generate a Lampada companion response",
    description=(
        "Sends the user message to the server-configured Gemini model. System "
        "instructions and the Gemini API key are never exposed to the client."
    ),
    responses={
        403: {"model": ErrorResponse, "description": "Invalid or missing API key"},
        429: {
            "model": ErrorResponse,
            "description": "Global or per-client request limit exceeded",
            "headers": {
                "Retry-After": {
                    "description": "Seconds until another request can be attempted",
                    "schema": {"type": "integer", "minimum": 1},
                }
            },
        },
        502: {"model": ErrorResponse, "description": "Gemini request failed"},
        503: {"model": ErrorResponse, "description": "Rate limiter unavailable"},
    },
)
async def lampada_complete(
    request: CompleteRequest,
    http_request: Request,
    api_key: bool = RequireAPIKey,
) -> CompleteResponse:
    client_key = resolve_client_ip(http_request)
    await _enforce_rate_limit(client_key)
    try:
        text = await complete(request.user)
    except GeminiError as error:
        # Log the failure category, but never the prayer text or provider key.
        logger.warning("Lampada AI request failed: %s", error)
        raise HTTPException(status_code=502, detail="AI service unavailable") from error
    return CompleteResponse(text=text)
