from collections import deque
import logging
import math
import re
import threading
import time
from typing import Any

import httpx
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from auth import RequireAPIKey
from config import GEMINI_API_KEY, GEMINI_MODEL, GEMINI_REQUESTS_PER_MINUTE


router = APIRouter()
MODEL_PATTERN = re.compile(r"^[a-zA-Z0-9._-]+$")
logger = logging.getLogger(__name__)
_request_times: deque[float] = deque()
_rate_limit_lock = threading.Lock()
_RATE_LIMIT_WINDOW_SECONDS = 60.0


class CompleteRequest(BaseModel):
    system: str = Field(
        min_length=1,
        max_length=8000,
        description="System instructions for the AI companion",
    )
    user: str = Field(
        min_length=1,
        max_length=16000,
        description="User message to answer",
    )


class CompleteResponse(BaseModel):
    text: str = Field(description="Text generated by the AI companion")


class GeminiError(RuntimeError):
    pass


def _enforce_rate_limit() -> None:
    now = time.monotonic()
    cutoff = now - _RATE_LIMIT_WINDOW_SECONDS

    with _rate_limit_lock:
        while _request_times and _request_times[0] <= cutoff:
            _request_times.popleft()

        if len(_request_times) >= GEMINI_REQUESTS_PER_MINUTE:
            retry_after = max(
                1,
                math.ceil(_RATE_LIMIT_WINDOW_SECONDS - (now - _request_times[0])),
            )
            raise HTTPException(
                status_code=429,
                detail="AI request limit exceeded",
                headers={"Retry-After": str(retry_after)},
            )

        _request_times.append(now)


def _extract_text(data: Any) -> str:
    try:
        parts = data["candidates"][0]["content"]["parts"]
    except (KeyError, IndexError, TypeError):
        return ""
    if not isinstance(parts, list):
        return ""
    return "".join(
        part.get("text", "")
        for part in parts
        if isinstance(part, dict) and isinstance(part.get("text"), str)
    ).strip()


async def complete(system: str, user: str) -> str:
    if not GEMINI_API_KEY:
        raise GeminiError("GEMINI_API_KEY is not configured")
    if not MODEL_PATTERN.fullmatch(GEMINI_MODEL):
        raise GeminiError("GEMINI_MODEL contains invalid characters")

    url = (
        "https://generativelanguage.googleapis.com/v1beta/models/"
        f"{GEMINI_MODEL}:generateContent"
    )
    payload = {
        "system_instruction": {"parts": [{"text": system}]},
        "contents": [{"role": "user", "parts": [{"text": user}]}],
        "generationConfig": {
            "maxOutputTokens": 1024,
            "temperature": 0.7,
        },
    }

    try:
        async with httpx.AsyncClient(timeout=20.0) as client:
            response = await client.post(
                url,
                headers={"x-goog-api-key": GEMINI_API_KEY},
                json=payload,
            )
            response.raise_for_status()
            data = response.json()
    except httpx.TimeoutException as error:
        raise GeminiError("Gemini request timed out") from error
    except (httpx.HTTPError, ValueError) as error:
        raise GeminiError("Gemini request failed") from error

    text = _extract_text(data)
    if not text:
        raise GeminiError("Gemini returned no text")
    return text


@router.post(
    "/lampada/v1/complete",
    response_model=CompleteResponse,
    operation_id="lampada_complete",
    tags=["Lampada"],
    summary="Generate a Lampada companion response",
    description=(
        "Sends system instructions and a user message to the server-configured "
        "Gemini model. The Gemini API key is never exposed to the client."
    ),
)
async def lampada_complete(
    request: CompleteRequest,
    api_key: bool = RequireAPIKey,
) -> CompleteResponse:
    _enforce_rate_limit()
    try:
        text = await complete(request.system, request.user)
    except GeminiError as error:
        # Log the failure category, but never the prayer text or provider key.
        logger.warning("Lampada AI request failed: %s", error)
        raise HTTPException(status_code=502, detail="AI service unavailable") from error
    return CompleteResponse(text=text)
