"""Post-filters for the leading question: gender, menus, tails.

ClickUp 86cbejvra (umbrella 86cbejvq1), from the independent assessment in
`evaluation/bench_data/question_comparison_prompt_v5_before_after/FABLE_ASSESSMENT.md`:
prompt wording did not fix three defects of Qwen3-30B, and the assessment's own
recommendation was to stop asking the model and to decide them in code.

* **Gender.** Prompt v5 says «do not default to the masculine» and Qwen obeys it
  *worse* than v4 did: 15 masculine addresses to a woman against 1. The person
  usually says their gender in their own first words («я рада», «заснула»,
  «втомилася»), so `detect_gender` reads it there and `gender_mismatch` says
  whether a candidate question addresses the other gender.
* **Menus.** «X или Y?» hands the person a closed choice instead of a question.
* **Tails.** «… — как ты будешь узнавать это?» is the shape the journal loop
  took: the same sentence with a new ending.

**Nothing here is wired into `app/twinkler_ai.py`.** This module is the
measurement instrument of 86cbejvra; whether the endpoint regenerates on a
verdict is a separate decision with its own ticket.

Dependency-free like `question_prompt.py` and `question_novelty.py`: the
standard library only, so the evaluation tools and the tests import it without
the application, and no environment variable can move any constant (ADR 0008).

## The constants

| constant | value | what it decides |
| --- | --- | --- |
| `FEMININE_SELF` / `MASCULINE_SELF` | 48 + 48 forms | which of the person's own words name their gender |
| `FEMININE_ADDRESS` / `MASCULINE_ADDRESS` | 47 + 52 forms | which forms in a question address a gendered «ты» |
| `AMBIGUOUS_ADDRESS` | `сам сама один одна` | address forms that also live as ordinary words («один день»), so they need a pronoun beside them |
| `ADDRESS_LOOKBACK` | 7 | how far back a gendered form looks for the second-person marker it belongs to |
| `AMBIGUOUS_LOOKBACK` | 2 | … for those four, where a distant pronoun is a measured false positive |
| `ADDRESS_LOOKAHEAD` | 2 | … and forward, for «услышала ли ты» word order |
| `MENU_CONJUNCTIONS` | `или чи or` | the conjunction a menu is built on |
| `MENU_MIN_SIDE_WORDS` | 2 | words each alternative needs, so «или» inside one phrase is not a menu |
| `TAIL_MIN_WORDS` | 3 | words after a dash that make it an appended clause rather than an aside |

Every list is **reviewed**, never generated by a rule like "words ending in
`-ла`". The reason is in the data: `series-exhaustion-uk` has the person write
«заснула» about herself and «колега звільнився» about someone else in the same
two sentences, and `gratitude-ru` has «сосед помог». A morphological rule reads
those as the person's own gender and gets both inputs wrong; a reviewed list
simply does not contain «звільнився» or «помог».

## What each function is, and is not

`detect_gender` is evidence about the person, not a claim about their identity:
it answers `None` whenever their words disagree or say nothing, and `None` is
the ordinary case (5 of the 16 benchmark inputs, plus every English one — the
language has no such forms and the lists carry none).

`gender_mismatch` at `gender=None` flags **any** explicit gendered address:
with no evidence, a gendered form is a gender the model imposed. That is the
column the assessment counts as «род навязан при неизвестном».

`is_menu` and `has_tail` are heuristics with **known false positives**, and are
meant for counting a corpus, not for rejecting one answer on their own:

* `is_menu` cannot tell «X или Y?» from «пять или шесть минут» or from a
  Ukrainian «чи» meaning "whether". Measured on the 396 benchmark answers it
  agrees with the manual count where the manual count exists; the disagreements
  are listed in `evaluation/README.md`, section «Промпт наводящего вопроса
  v6-A».
* `has_tail` counts every dash with a clause after it, including the ones that
  carry the whole point of the question («что именно — в деталях, в ритме —
  делает…»). It measures a shape, not a defect.

## Measured against the manual count

`tests/test_question_filters.py` runs this module over all 396 answers of the
four benchmark artifacts (Qwen and Gemini, prompts v4 and v5) and pins the
numbers. Against the hand count in `FABLE_ASSESSMENT.md`, «Род и язык»:

| combination | manual (wrong gender + imposed) | this module | rows |
| --- | --- | --- | --- |
| Qwen / v4 | 1 + 3 | **1 + 3** | the same rows |
| Qwen / v5 | 15 + 4 | **15 + 4** | the same rows |
| Gemini / v4 | 0 + 2 | 1 + 2 | one extra, below |
| Gemini / v5 | 0 + 0 | **0 + 0** | — |

The single disagreement is `series-gratitude-ru` sample 2 step 4 of Gemini/v4,
«Что ты чувствовала, когда отчёт **был наконец готов**?»: «готов» is a
masculine short adjective agreeing with «отчёт», six words after the «ты» that
the window rule attaches it to. It is a false positive of the window, not of
the list, and it is left in rather than tuned away — the alternative was a
narrower window that drops a real miss (`series-scale-ru` s2 st6 of Qwen/v5,
«даже если не уверен», also six words out), and tuning a rule until one corpus
comes out right is how a detector stops measuring anything.

**That row is one instance of a whole class, and the class is wider than a
short adjective.** `_addresses_the_person` attaches a gendered form to the
nearest *pronoun*; a third-person **noun** subject standing between the
pronoun and the form is invisible to it, because nothing here does morphology.
So every sentence of the shape "«ты» … <noun> <gendered verb>" is flagged:

* «Что ты почувствовала, когда **твой муж сказал** тебе об этом?» → `{f, m}`
* «Что ты почувствовала, когда **малыш заснул** у тебя на руках?» → `{f, m}`
* «Что ты чувствовала, когда **отчёт был** наконец готов?» → `{f, m}`

Only a third-person *pronoun* stops the scan («что **он** хотел» is correctly
ignored). The class costs one row in 396 here, and it is a floor on how far
this heuristic can be trusted: a verdict of "wrong gender" on a single answer
must be read, not acted on, and a genuine fix is morphological agreement,
which this module deliberately does not attempt.
"""

from __future__ import annotations

import re
from collections.abc import Sequence

# --- tokenisation ----------------------------------------------------------
# The same normalisation `question_novelty` uses, kept local rather than
# imported: these two modules answer different questions and neither should
# start depending on the other's spelling rules. Casefold, ё→е (Russian spells
# the same word both ways), everything that is not a word character or space
# becomes a space. Ukrainian `і`, `ї`, `є`, `ґ` are word characters and survive;
# the apostrophe of «сім'ю» is not, so that word splits — harmless here, since
# no list below contains an apostrophe.
_NON_WORD = re.compile(r"[^\w\s]", re.UNICODE)


def words(text: str) -> list[str]:
    """The text as normalized word tokens."""
    return _NON_WORD.sub(" ", text.casefold().replace("ё", "е")).split()


# --- 1. the person's own gender --------------------------------------------
# First-person self-report forms, ru and uk, in feminine/masculine pairs. Only
# verbs and adjectives a person uses ABOUT THEMSELVES in a prayer journal are
# here: «сказала», «пришла», «была» and their masculine twins are deliberately
# absent, because they are exactly as likely to be about a husband, a sister or
# a colleague. See the docstring.
_SELF_PAIRS: tuple[tuple[str, str], ...] = (
    # ru — the forms the benchmark inputs actually contain, first
    ("рада", "рад"),
    ("сделала", "сделал"),
    ("ответила", "ответил"),
    ("успела", "успел"),
    ("поняла", "понял"),
    ("увиделась", "увиделся"),
    ("молилась", "молился"),
    ("отправила", "отправил"),
    ("заснула", "заснул"),
    ("верила", "верил"),
    # ru — the rest of the reviewed set
    ("смогла", "смог"),
    ("устала", "устал"),
    ("проснулась", "проснулся"),
    ("справилась", "справился"),
    ("вернулась", "вернулся"),
    ("решила", "решил"),
    ("написала", "написал"),
    ("забыла", "забыл"),
    ("начала", "начал"),
    ("закончила", "закончил"),
    ("испугалась", "испугался"),
    ("разозлилась", "разозлился"),
    ("расстроилась", "расстроился"),
    ("обрадовалась", "обрадовался"),
    ("обещала", "обещал"),
    ("ждала", "ждал"),
    ("работала", "работал"),
    ("думала", "думал"),
    ("чувствовала", "чувствовал"),
    ("плакала", "плакал"),
    ("молчала", "молчал"),
    ("хотела", "хотел"),
    ("успокоилась", "успокоился"),
    ("собралась", "собрался"),
    # uk
    ("втомилася", "втомився"),
    ("раділа", "радів"),
    ("зробила", "зробив"),
    ("змогла", "зміг"),
    ("зрозуміла", "зрозумів"),
    ("відповіла", "відповів"),
    ("прокинулася", "прокинувся"),
    ("вимкнула", "вимкнув"),
    ("почувалася", "почувався"),
    ("хотіла", "хотів"),
    ("працювала", "працював"),
    ("встигла", "встиг"),
    ("вирішила", "вирішив"),
    ("чекала", "чекав"),
)
FEMININE_SELF = frozenset(pair[0] for pair in _SELF_PAIRS)
MASCULINE_SELF = frozenset(pair[1] for pair in _SELF_PAIRS)

FEMININE = "f"
MASCULINE = "m"


def detect_gender(person_texts: Sequence[str]) -> str | None:
    """The person's grammatical gender from their own words, or `None`.

    `person_texts` is what the person wrote: the topic of the prayer and their
    `user` turns. English text says nothing (the lists hold no English), and
    neither does a person who simply did not use a gendered form — both answer
    `None`, which is the ordinary case rather than a failure.

    Words of **both** genders answer `None` as well: one of them is about
    somebody else, and there is no way to tell which, so a request that carries
    a contradiction is treated as carrying no evidence.
    """
    feminine = masculine = False
    for text in person_texts:
        for word in words(text):
            if word in FEMININE_SELF:
                feminine = True
            elif word in MASCULINE_SELF:
                masculine = True
    if feminine == masculine:  # both, or neither
        return None
    return FEMININE if feminine else MASCULINE


# --- 2. the gender a question addresses ------------------------------------
# Forms that address the person: «ты сделала», «ти зробив», «должен», «сама».
# Same pairing discipline; a form is here only if a question asking it of the
# person reads naturally.
_ADDRESS_PAIRS: tuple[tuple[str, str], ...] = (
    # ru
    ("думала", "думал"),
    ("заметила", "заметил"),
    ("должна", "должен"),
    ("готова", "готов"),
    ("уверена", "уверен"),
    ("сама", "сам"),
    ("одна", "один"),
    ("хотела", "хотел"),
    ("сделала", "сделал"),
    ("сказала", "сказал"),
    ("поняла", "понял"),
    ("почувствовала", "почувствовал"),
    ("чувствовала", "чувствовал"),
    ("смогла", "смог"),
    ("могла", "мог"),
    ("подумала", "подумал"),
    ("стала", "стал"),
    ("решила", "решил"),
    ("ждала", "ждал"),
    ("увидела", "увидел"),
    ("услышала", "услышал"),
    ("написала", "написал"),
    ("начала", "начал"),
    ("закончила", "закончил"),
    ("вспомнила", "вспомнил"),
    ("ответила", "ответил"),
    ("успела", "успел"),
    ("назвала", "назвал"),
    ("запланировала", "запланировал"),
    ("обещала", "обещал"),
    ("выбрала", "выбрал"),
    ("заснула", "заснул"),
    ("молилась", "молился"),
    ("осталась", "остался"),
    ("держалась", "держался"),
    # uk
    ("зробила", "зробив"),
    ("могла", "міг"),
    ("повинна", "повинен"),
    ("відчула", "відчув"),
    ("змогла", "зміг"),
    ("хотіла", "хотів"),
    ("вагалася", "вагався"),
    ("помітила", "помітив"),
    ("зрозуміла", "зрозумів"),
    ("сказала", "сказав"),
    ("готова", "готовий"),
    ("впевнена", "впевнений"),
    ("залишилася", "залишився"),
    ("робила", "робив"),
    ("заснула", "заснув"),
    ("втомилася", "втомився"),
    ("думала", "думав"),
)
FEMININE_ADDRESS = frozenset(pair[0] for pair in _ADDRESS_PAIRS)
MASCULINE_ADDRESS = frozenset(pair[1] for pair in _ADDRESS_PAIRS)

# «сам», «сама», «один», «одна» are also ordinary words — «на один день», «сама
# по себе мысль». They count only with a second-person pronoun beside them.
AMBIGUOUS_ADDRESS = frozenset({"сам", "сама", "один", "одна"})

# Whom a gendered form belongs to is decided by the nearest second-person
# marker. Seven words back covers «Что из завтрашних дел ты уже сейчас видишь
# как необходимое, даже если не уверен»; two forward cover the inverted
# «услышала ли ты». The ambiguous four get a much tighter window — see below.
ADDRESS_LOOKBACK = 7
ADDRESS_LOOKAHEAD = 2
AMBIGUOUS_LOOKBACK = 2
_SECOND_PERSON = frozenset({
    "ты", "тебя", "тебе", "тобой", "тобою", "твой", "твоя", "твое",
    "твои", "твоим", "твоей", "твоего", "твоих",
    "ти", "тобі", "твій", "твоє", "твої", "твоїм", "твоєї",
})
_THIRD_PERSON = frozenset({
    "он", "она", "оно", "они", "его", "ее", "их", "ней", "нее", "него",
    "них", "нею", "ним", "ними",
    "він", "вона", "воно", "вони", "його", "її", "їх", "їм", "ними",
})
# A second-person singular verb is a second-person marker too, and it is the
# only one many questions carry: «Що відчуваєш, коли … що хотів зробити».
# A suffix rule rather than a list, because the verb itself is unbounded.
#
# The length floor is where the rule stops, and it is a trade measured rather
# than assumed. At 6 the nouns that end the same way are out of reach — «тишь»,
# uk «миш», and «малыш», which at 5 makes «Малыш заснул, а что осталось с
# тобой?» look like an address. The price is that the genuine five-letter
# second-person verbs stop being markers: «хочеш», «можеш», «робиш», «бачиш»,
# «кажеш», «мрієш», «ждешь», «идешь» — all eight occur in the benchmark
# answers. Neither side of the trade moves a single verdict on the 846 measured
# answers (396 of the four comparison artifacts + 450 of the six sampling runs
# of 86cbejvra), because a question carrying one of those verbs carries a
# second-person pronoun too; so the floor decides the rule's reach, not this
# corpus, and 6 is the conservative end of it.
#
# It does NOT close the false-positive class of `_addresses_the_person` below:
# «Что ты почувствовала, когда малыш заснул…» is flagged at either floor,
# because «ты» is the marker there.
_SECOND_PERSON_VERB = re.compile(
    r"(?:ешь|ишь|ешься|ишься|єш|еш|иш|їш|єшся|ешся|ишся|їшся)$"
)
_MIN_VERB_LENGTH = 6


def _is_second_person(token: str) -> bool:
    return token in _SECOND_PERSON or (
        len(token) >= _MIN_VERB_LENGTH and bool(_SECOND_PERSON_VERB.search(token))
    )


def _addresses_the_person(tokens: Sequence[str], index: int) -> bool:
    """Is the gendered form at `index` addressed to the person?

    The nearest marker decides. A second-person one first — «ты … сделала»,
    «відчуваєш … хотів» — means the form is an address; a third-person pronoun
    first — «что он хотел» — means it is about somebody else and this module
    says nothing about it. With no marker in the window the form is not
    counted: counting a bare participle would flag «какой была эта тишина».

    **A third-person NOUN subject does not stop the scan** — «когда твой муж
    сказал», «когда малыш заснул», «когда отчёт был готов» all read as
    addresses. That is the documented false-positive class of this module (see
    the docstring); closing it needs morphological agreement, not a narrower
    window — a narrower window loses real findings at the same distance.

    `AMBIGUOUS_ADDRESS` («сам», «одна», …) uses `AMBIGUOUS_LOOKBACK` instead,
    and the reason is a measured false positive: «важно для тебя — не просто
    результат, а сам акт делать» has «тебя» five words before a «сам» that
    means "the act itself". Those four words are an address only when the
    pronoun is next to them («ты сам», «ты не одна»).
    """
    lookback = (
        AMBIGUOUS_LOOKBACK if tokens[index] in AMBIGUOUS_ADDRESS else ADDRESS_LOOKBACK
    )
    for step in range(1, lookback + 1):
        position = index - step
        if position < 0:
            break
        if _is_second_person(tokens[position]):
            return True
        if tokens[position] in _THIRD_PERSON:
            return False
    for step in range(1, ADDRESS_LOOKAHEAD + 1):
        position = index + step
        if position >= len(tokens):
            break
        if _is_second_person(tokens[position]):
            return True
        if tokens[position] in _THIRD_PERSON:
            return False
    return False


def addressed_genders(question: str) -> set[str]:
    """Which genders this question addresses the person in — `f`, `m`, both."""
    tokens = words(question)
    found: set[str] = set()
    for index, token in enumerate(tokens):
        feminine = token in FEMININE_ADDRESS
        masculine = token in MASCULINE_ADDRESS
        if not feminine and not masculine:
            continue
        # `AMBIGUOUS_ADDRESS` needs the pronoun for a different reason than the
        # rest — «один день» is not an address at all — but the same test
        # answers both, so there is one call and one rule.
        if not _addresses_the_person(tokens, index):
            continue
        # A form that is feminine in one language and masculine in the other
        # would be undecidable; there is none in the lists, and a future one
        # would show up as "both" rather than as a silent choice.
        if feminine:
            found.add(FEMININE)
        if masculine:
            found.add(MASCULINE)
    return found


def gender_mismatch(question: str, gender: str | None) -> bool:
    """Does this question address the person as the wrong gender?

    With a known `gender`, a mismatch is an address in the other one. With
    `gender is None` — the person's words say nothing — **any** explicit
    gendered address is a mismatch: the model imposed a gender the request did
    not carry, and half the time it will be wrong.
    """
    addressed = addressed_genders(question)
    if not addressed:
        return False
    if gender is None:
        return True
    return any(other != gender for other in addressed)


# --- 3. a menu instead of a question ---------------------------------------
MENU_CONJUNCTIONS = frozenset({"или", "чи", "or"})
MENU_MIN_SIDE_WORDS = 2


def is_menu(question: str) -> bool:
    """Does this question offer a closed choice — «X или Y?»

    Heuristic, and it says so: a conjunction that is not the first words of the
    question and has at least `MENU_MIN_SIDE_WORDS` words on either side. That
    catches «то, что вы смеялись, или то, что вы снова оказались рядом?» and
    misses nothing the assessment counted by hand — but it also cannot tell an
    alternative from «пять или шесть минут», from a Ukrainian «чи» meaning
    "whether", or from an English «or» inside one noun phrase. False positives
    are acceptable for counting a corpus and are the reason this verdict is not
    a rejection on its own.
    """
    tokens = words(question)
    for index, token in enumerate(tokens):
        if token not in MENU_CONJUNCTIONS:
            continue
        if index >= MENU_MIN_SIDE_WORDS and (
            len(tokens) - index - 1 >= MENU_MIN_SIDE_WORDS
        ):
            return True
    return False


# --- 4. an appended tail ---------------------------------------------------
TAIL_MIN_WORDS = 3
# A dash with spaces on both sides — em, en or plain hyphen. A hyphen inside a
# word («что-то») has no spaces and is not one.
_DASH = re.compile(r"\s[—–-]\s")
# «не просто X, а Y» and its two siblings: the same appended clause built out of
# words instead of punctuation.
_NOT_JUST = (
    re.compile(r"\bне\s+просто\b.{1,200}?\bа\b", re.IGNORECASE | re.DOTALL),
    re.compile(r"\bне\s+лише\b.{1,200}?\bа\b", re.IGNORECASE | re.DOTALL),
    re.compile(r"\bnot\s+just\b.{1,200}?\bbut\b", re.IGNORECASE | re.DOTALL),
)


def has_tail(question: str) -> bool:
    """Is a clause appended to this question after a dash — or a «не просто … а …»?

    The shape the journal loop took: one sentence reused with a new ending. A
    dash counts only when at least `TAIL_MIN_WORDS` words follow it, so a
    parenthetical dash pair in the middle («что именно — в деталях — делает»)
    is judged by what comes after the LAST dash, and a trailing «— как?» is not
    a tail either.

    This counts a shape, not a defect: the dash frequently carries the point of
    the question. Read the number, do not act on one verdict.
    """
    for match in _DASH.finditer(question):
        if len(words(question[match.end():])) >= TAIL_MIN_WORDS:
            return True
    return any(pattern.search(question) for pattern in _NOT_JUST)
