import base64
import logging
import re
from typing import Any

import httpx
from fastapi import APIRouter, File, Form, HTTPException, Request, UploadFile
from pydantic import BaseModel, ConfigDict, Field

from auth import RequireAPIKey
from client_ip import resolve_client_ip
from config import (
    GEMINI_API_KEY,
    AI_QUESTION_MODEL,
    AI_QUESTION_TIMEOUT_SECONDS,
    AI_TRANSCRIBE_MODEL,
    AI_REQUESTS_PER_CLIENT_PER_MINUTE,
    AI_REQUESTS_PER_MINUTE,
    QUESTION_PROVIDER,
)
from llm_client import AsyncChatClient, LLMError
from question_prompt import build_question_prompt
from rate_limit import RateLimiter, RateLimitError
from safety import (
    SAFETY_REPLY_VERSION,
    check_input,
    check_reply,
    detect_language,
    safety_reply,
)

router = APIRouter()
MODEL_PATTERN = re.compile(r"^[a-zA-Z0-9._-]+$")
LOCALE_PATTERN = re.compile(r"^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$")
logger = logging.getLogger(__name__)
# Inline data is base64-expanded inside Gemini's 20 MB request limit.
_MAX_AUDIO_BYTES = 14 * 1024 * 1024
_AUDIO_MIME_TYPES = frozenset({"audio/mp4", "audio/x-m4a", "audio/m4a"})
_M4A_FALLBACK_MIME_TYPES = frozenset({"", "application/octet-stream"})
_TRANSCRIPTION_PROMPT = (
    "Transcribe the speech verbatim in its original language. Preserve "
    "code-switching. Do not translate, summarize, add, omit, explain, or "
    "rewrite anything. Add only natural punctuation. Return only the transcript."
)
_limiter = RateLimiter(name="AI")
# Historical module-level names, kept as aliases of the very same deques so
# diagnostics and tests can inspect the limiter state directly.
_request_times = _limiter.request_times
_client_request_times = _limiter.client_request_times


class CompleteRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    user: str = Field(
        min_length=1,
        max_length=16000,
        description="User message to answer",
    )


class CompleteResponse(BaseModel):
    text: str = Field(description="Text generated by the AI companion")


class ErrorResponse(BaseModel):
    detail: str = Field(description="Public error message")


class AIError(RuntimeError):
    """One AI call of this module failed, whichever provider served it."""


# The historical name, kept as an alias: it is the exception both handlers
# catch and the one tests raise. Since ADR 0009 the question stage may run on
# an OpenAI-compatible endpoint, so the *class* is provider-independent while
# the name stays what every caller already imports.
GeminiError = AIError


def question_prompt_for(text: str) -> str:
    """The system prompt to answer `text` with (prompt v2, ClickUp 86cbegg3f).

    One seam, on purpose: the prompt needs a *language*, and the language
    comes from whatever text the caller considers the person's own words.
    Today `POST /api/ai/question` takes a single `user` field carrying the
    whole conversation, so that whole string is what is passed. When the
    request becomes structured (topic + stage + messages, ClickUp 86cbegmzz)
    the caller passes the last user message here instead and nothing else
    changes — the detector is a pure function of the text it is given, and
    `build_question_prompt` never sees the request shape at all.
    """
    return build_question_prompt(detect_language(text))


def _reserve_rate_limit(client_key: str) -> None:
    """Book one Twinkler AI slot; limits are read at call time."""
    _limiter.reserve(
        client_key,
        AI_REQUESTS_PER_MINUTE,
        AI_REQUESTS_PER_CLIENT_PER_MINUTE,
    )


async def _enforce_rate_limit(client_key: str) -> None:
    try:
        _reserve_rate_limit(client_key)
    except RateLimitError as error:
        if error.retry_after is not None:
            raise HTTPException(
                status_code=429,
                detail="AI request limit exceeded",
                headers={"Retry-After": str(error.retry_after)},
            ) from error
        logger.warning("Twinkler rate limiter unavailable: %s", error)
        raise HTTPException(
            status_code=503,
            detail="AI service temporarily unavailable",
        ) from error


def _extract_text(data: Any) -> str:
    try:
        parts = data["candidates"][0]["content"]["parts"]
    except (KeyError, IndexError, TypeError):
        return ""
    if not isinstance(parts, list):
        return ""
    return "".join(
        part.get("text", "")
        for part in parts
        if isinstance(part, dict) and isinstance(part.get("text"), str)
    ).strip()


async def _complete_openai_compat(user: str, prompt: str) -> str:
    """The question stage on an OpenAI-compatible endpoint (ADR 0009).

    Same prompt (built once by the caller, so both transports send the same
    bytes), same generation settings (temperature
    0.7, 1024 output tokens) and the same public failure — `AIError`, which
    the handler turns into `502 AI service unavailable` without provider
    detail. `json_object` is deliberately off: this answer is prose for a
    person, not a parsed contract.

    One attempt, like the Gemini path: this endpoint has no request budget to
    plan a retry ladder inside, and a second call would double the worst-case
    latency a person waits with no message on screen.
    """
    client = AsyncChatClient(
        QUESTION_PROVIDER.endpoint,
        QUESTION_PROVIDER.api_key,
        QUESTION_PROVIDER.model,
        timeout=AI_QUESTION_TIMEOUT_SECONDS,
        attempts=1,
    )
    try:
        text = await client.complete(
            prompt, user, json_object=False, temperature=0.7
        )
    except LLMError as error:
        raise AIError(f"question failed: {error}") from None
    if not text:
        raise AIError("AI returned no text")
    return text


async def complete(user: str) -> str:
    """Answer one user message, or raise AIError (the caller's 502).

    "AI is not configured" is decided by exactly two variables since
    2026-08-30, and the prompt is no longer one of them:
    `GEMINI_API_KEY` unset -> GeminiError here -> 502, and
    `AI_CLIENT_HMAC_KEY` unset -> the limiter fails closed before this
    function is reached -> 503 (see `_enforce_rate_limit`). A malformed
    `AI_QUESTION_MODEL` is also a 502, but is unreachable in practice: with
    a key set, an unnamed model aborts startup (ADR 0008).

    Since 2026-08-30 the system prompt is code
    (`app/question_prompt.py`), so the two guards this function used
    to carry — "prompt is not configured" and "prompt is too long" — are
    gone: neither can be true of a reviewed literal, and keeping them would
    have pretended a code change could arrive at runtime. What remains
    configurable is exactly what the deployment supplies: the provider (ADR
    0009), the key and the model name.

    Since prompt v2 (2026-09-05, ClickUp 86cbegg3f) the prompt names the
    language to answer in, resolved by `safety.detect_language` — the same
    detector the despair rule runs on the same message, never a second one.
    It is resolved ONCE, through `question_prompt_for`, and handed to
    whichever transport answers, so the two providers keep sending identical
    bytes.
    """
    prompt = question_prompt_for(user)
    if QUESTION_PROVIDER.is_openai_compat:
        return await _complete_openai_compat(user, prompt)
    if not GEMINI_API_KEY:
        raise GeminiError("GEMINI_API_KEY is not configured")
    if not MODEL_PATTERN.fullmatch(AI_QUESTION_MODEL):
        raise GeminiError("AI_QUESTION_MODEL contains invalid characters")

    url = (
        "https://generativelanguage.googleapis.com/v1beta/models/"
        f"{AI_QUESTION_MODEL}:generateContent"
    )
    payload = {
        "system_instruction": {"parts": [{"text": prompt}]},
        "contents": [{"role": "user", "parts": [{"text": user}]}],
        "generationConfig": {
            "maxOutputTokens": 1024,
            "temperature": 0.7,
        },
    }

    try:
        # The same knob the openai_compat branch honours
        # (`AI_QUESTION_TIMEOUT_SECONDS`, default 20.0 = the literal this
        # replaces): a variable documented as "the ceiling of the question
        # endpoint's single call" must not be silently ignored on one of the
        # two providers. Still a bare number here, i.e. per httpx PHASE, which
        # is exactly what this call has always done — carving it the way
        # `gemini_retry.provider_timeout` does would be a behaviour change to
        # the Gemini path, and this endpoint has no request budget to carve.
        async with httpx.AsyncClient(timeout=AI_QUESTION_TIMEOUT_SECONDS) as client:
            response = await client.post(
                url,
                headers={"x-goog-api-key": GEMINI_API_KEY},
                json=payload,
            )
            response.raise_for_status()
            data = response.json()
    except httpx.TimeoutException as error:
        raise GeminiError("Gemini request timed out") from error
    except (httpx.HTTPError, ValueError) as error:
        raise GeminiError("Gemini request failed") from error

    text = _extract_text(data)
    if not text:
        raise GeminiError("Gemini returned no text")
    return text


def _audio_mime_type(file: UploadFile) -> str:
    content_type = (file.content_type or "").split(";", 1)[0].strip().lower()
    if content_type in _AUDIO_MIME_TYPES:
        return content_type

    filename = file.filename or ""
    if filename.lower().endswith(".m4a") and content_type in _M4A_FALLBACK_MIME_TYPES:
        return "audio/mp4"

    raise HTTPException(status_code=415, detail="Unsupported audio format")


def _transcription_prompt(locale: str | None) -> str:
    if locale is None:
        return _TRANSCRIPTION_PROMPT
    return (
        f"{_TRANSCRIPTION_PROMPT} The app locale is {locale}; use it only as a "
        "weak hint when the spoken language is ambiguous."
    )


async def transcribe(audio: bytes, mime_type: str, locale: str | None) -> str:
    """Transcribe one recording with Gemini, or raise AIError (a 502).

    Deliberately Gemini-only, with no `AI_TRANSCRIBE_PROVIDER` to switch
    (config refuses that variable): speech is the one stage the
    OpenAI-compatible chat protocol does not cover, and it moves to a local
    speech model in its own step. So a deployment whose three CHAT stages run
    on another provider still needs `GEMINI_API_KEY` for this endpoint — and
    without one it answers the same explicit 502 it always has, while
    everything else keeps working.
    """
    if not GEMINI_API_KEY:
        raise GeminiError("GEMINI_API_KEY is not configured")
    if not MODEL_PATTERN.fullmatch(AI_TRANSCRIBE_MODEL):
        raise GeminiError("AI_TRANSCRIBE_MODEL contains invalid characters")

    url = (
        "https://generativelanguage.googleapis.com/v1beta/models/"
        f"{AI_TRANSCRIBE_MODEL}:generateContent"
    )
    payload = {
        "contents": [{
            "role": "user",
            "parts": [
                {"text": _transcription_prompt(locale)},
                {
                    "inline_data": {
                        "mime_type": mime_type,
                        "data": base64.b64encode(audio).decode("ascii"),
                    }
                },
            ],
        }],
        "generationConfig": {
            "maxOutputTokens": 4096,
            "temperature": 0,
        },
    }

    try:
        async with httpx.AsyncClient(timeout=60.0) as client:
            response = await client.post(
                url,
                headers={"x-goog-api-key": GEMINI_API_KEY},
                json=payload,
            )
            response.raise_for_status()
            data = response.json()
    except httpx.TimeoutException as error:
        raise GeminiError("Gemini transcription timed out") from error
    except (httpx.HTTPError, ValueError) as error:
        raise GeminiError("Gemini transcription failed") from error

    text = _extract_text(data)
    if not text:
        raise GeminiError("Gemini returned no transcript")
    return text


@router.post(
    "/ai/question",
    response_model=CompleteResponse,
    operation_id="ai_question",
    tags=["AI"],
    summary="Generate an AI companion response",
    description=(
        "Sends the user message to the server-configured AI model with a "
        "server-side system prompt. The provider API key is never exposed to "
        "the client. A message showing despair or self-harm is answered with "
        "a fixed supportive text in the same language and no model is called."
    ),
    responses={
        403: {"model": ErrorResponse, "description": "Invalid or missing API key"},
        429: {
            "model": ErrorResponse,
            "description": "Global or per-client request limit exceeded",
            "headers": {
                "Retry-After": {
                    "description": "Seconds until another request can be attempted",
                    "schema": {"type": "integer", "minimum": 1},
                }
            },
        },
        # Public wording only: the exact server-side conditions behind these
        # two codes are documented in architect/twinkler-ai.md, not in a spec
        # the client reads — naming server variables there would leak
        # deployment detail for no consumer benefit.
        502: {
            "model": ErrorResponse,
            "description": "AI is not configured or the provider request failed",
        },
        503: {"model": ErrorResponse, "description": "Rate limiter unavailable"},
    },
)
async def twinkler_complete(
    request: CompleteRequest,
    http_request: Request,
    api_key: bool = RequireAPIKey,
) -> CompleteResponse:
    client_key = resolve_client_ip(http_request)
    await _enforce_rate_limit(client_key)

    # The despair rule is code, not an instruction a provider may or may not
    # follow (app/safety.py, ClickUp 86cbegg23). Tier 1 answers here and the
    # model is never called; the reservation above is deliberately kept — the
    # client got a reply, and the quota must not depend on what was in it.
    finding = check_input(request.user)
    if finding.matched:
        logger.warning(
            "Safety rule fired on the request: tier=%d pattern=%s language=%s "
            "reply_version=%d",
            finding.tier,
            finding.pattern_id,
            finding.language,
            SAFETY_REPLY_VERSION,
        )
        return CompleteResponse(text=safety_reply(finding.language))

    try:
        text = await complete(request.user)
    except GeminiError as error:
        # Log the failure category, but never the prayer text or provider key.
        logger.warning("Twinkler AI request failed: %s", error)
        raise HTTPException(status_code=502, detail="AI service unavailable") from error

    # Tier 2: the message carried a weaker despair signal and the model
    # answered it with a question anyway. Replace the answer, keep the fact.
    guard = check_reply(request.user, text)
    if guard.matched:
        logger.warning(
            "Safety rule fired on the model reply: tier=%d pattern=%s "
            "language=%s reply_version=%d",
            guard.tier,
            guard.pattern_id,
            guard.language,
            SAFETY_REPLY_VERSION,
        )
        text = safety_reply(guard.language)
    return CompleteResponse(text=text)


@router.post(
    "/ai/transcribe",
    response_model=CompleteResponse,
    operation_id="ai_transcribe",
    tags=["AI"],
    summary="Transcribe a voice recording",
    description=(
        "Transcribes an M4A recording in its original language. The optional "
        "locale is used only as a weak language hint."
    ),
    responses={
        403: {"model": ErrorResponse, "description": "Invalid or missing API key"},
        413: {"model": ErrorResponse, "description": "Audio file is too large"},
        415: {"model": ErrorResponse, "description": "Unsupported audio format"},
        429: {
            "model": ErrorResponse,
            "description": "Global or per-client request limit exceeded",
            "headers": {
                "Retry-After": {
                    "description": "Seconds until another request can be attempted",
                    "schema": {"type": "integer", "minimum": 1},
                }
            },
        },
        502: {"model": ErrorResponse, "description": "Gemini request failed"},
        503: {"model": ErrorResponse, "description": "Rate limiter unavailable"},
    },
)
async def twinkler_transcribe(
    http_request: Request,
    file: UploadFile = File(..., description="M4A voice recording"),
    locale: str | None = Form(
        default=None,
        max_length=35,
        description="Optional BCP 47 app locale used only as a weak hint",
    ),
    api_key: bool = RequireAPIKey,
) -> CompleteResponse:
    if locale is not None and not LOCALE_PATTERN.fullmatch(locale):
        raise HTTPException(status_code=422, detail="Invalid locale")

    try:
        mime_type = _audio_mime_type(file)
        audio = await file.read(_MAX_AUDIO_BYTES + 1)
    finally:
        await file.close()

    if not audio:
        raise HTTPException(status_code=422, detail="Audio file is empty")
    if len(audio) > _MAX_AUDIO_BYTES:
        raise HTTPException(status_code=413, detail="Audio file is too large")

    client_key = resolve_client_ip(http_request)
    await _enforce_rate_limit(client_key)

    try:
        text = await transcribe(audio, mime_type, locale)
    except GeminiError as error:
        # Keep this static: provider errors must never leak recording metadata.
        logger.warning("Twinkler transcription request failed")
        raise HTTPException(status_code=502, detail="AI service unavailable") from error
    return CompleteResponse(text=text)
