import base64
import logging
import re
from typing import Any

import httpx
from fastapi import APIRouter, File, Form, HTTPException, Request, UploadFile
from pydantic import BaseModel, ConfigDict, Field

from auth import RequireAPIKey
from client_ip import resolve_client_ip
from config import (
    GEMINI_API_KEY,
    GEMINI_MODEL,
    GEMINI_TRANSCRIPTION_MODEL,
    GEMINI_REQUESTS_PER_CLIENT_PER_MINUTE,
    GEMINI_REQUESTS_PER_MINUTE,
    TWINKLER_SYSTEM_PROMPT,
)
from rate_limit import RateLimiter, RateLimitError

router = APIRouter()
MODEL_PATTERN = re.compile(r"^[a-zA-Z0-9._-]+$")
LOCALE_PATTERN = re.compile(r"^[A-Za-z]{2,3}(?:-[A-Za-z0-9]{2,8})*$")
logger = logging.getLogger(__name__)
# Inline data is base64-expanded inside Gemini's 20 MB request limit.
_MAX_AUDIO_BYTES = 14 * 1024 * 1024
_AUDIO_MIME_TYPES = frozenset({"audio/mp4", "audio/x-m4a", "audio/m4a"})
_M4A_FALLBACK_MIME_TYPES = frozenset({"", "application/octet-stream"})
_TRANSCRIPTION_PROMPT = (
    "Transcribe the speech verbatim in its original language. Preserve "
    "code-switching. Do not translate, summarize, add, omit, explain, or "
    "rewrite anything. Add only natural punctuation. Return only the transcript."
)
_limiter = RateLimiter(name="AI")
# Historical module-level names, kept as aliases of the very same deques so
# diagnostics and tests can inspect the limiter state directly.
_request_times = _limiter.request_times
_client_request_times = _limiter.client_request_times


class CompleteRequest(BaseModel):
    model_config = ConfigDict(extra="forbid")

    user: str = Field(
        min_length=1,
        max_length=16000,
        description="User message to answer",
    )


class CompleteResponse(BaseModel):
    text: str = Field(description="Text generated by the AI companion")


class ErrorResponse(BaseModel):
    detail: str = Field(description="Public error message")


class GeminiError(RuntimeError):
    pass


def _reserve_rate_limit(client_key: str) -> None:
    """Book one Twinkler AI slot; limits are read at call time."""
    _limiter.reserve(
        client_key,
        GEMINI_REQUESTS_PER_MINUTE,
        GEMINI_REQUESTS_PER_CLIENT_PER_MINUTE,
    )


async def _enforce_rate_limit(client_key: str) -> None:
    try:
        _reserve_rate_limit(client_key)
    except RateLimitError as error:
        if error.retry_after is not None:
            raise HTTPException(
                status_code=429,
                detail="AI request limit exceeded",
                headers={"Retry-After": str(error.retry_after)},
            ) from error
        logger.warning("Twinkler rate limiter unavailable: %s", error)
        raise HTTPException(
            status_code=503,
            detail="AI service temporarily unavailable",
        ) from error


def _extract_text(data: Any) -> str:
    try:
        parts = data["candidates"][0]["content"]["parts"]
    except (KeyError, IndexError, TypeError):
        return ""
    if not isinstance(parts, list):
        return ""
    return "".join(
        part.get("text", "")
        for part in parts
        if isinstance(part, dict) and isinstance(part.get("text"), str)
    ).strip()


async def complete(user: str) -> str:
    if not GEMINI_API_KEY:
        raise GeminiError("GEMINI_API_KEY is not configured")
    if not TWINKLER_SYSTEM_PROMPT:
        raise GeminiError("TWINKLER_SYSTEM_PROMPT is not configured")
    if len(TWINKLER_SYSTEM_PROMPT) > 8000:
        raise GeminiError("TWINKLER_SYSTEM_PROMPT is too long")
    if not MODEL_PATTERN.fullmatch(GEMINI_MODEL):
        raise GeminiError("GEMINI_MODEL contains invalid characters")

    url = (
        "https://generativelanguage.googleapis.com/v1beta/models/"
        f"{GEMINI_MODEL}:generateContent"
    )
    payload = {
        "system_instruction": {"parts": [{"text": TWINKLER_SYSTEM_PROMPT}]},
        "contents": [{"role": "user", "parts": [{"text": user}]}],
        "generationConfig": {
            "maxOutputTokens": 1024,
            "temperature": 0.7,
        },
    }

    try:
        async with httpx.AsyncClient(timeout=20.0) as client:
            response = await client.post(
                url,
                headers={"x-goog-api-key": GEMINI_API_KEY},
                json=payload,
            )
            response.raise_for_status()
            data = response.json()
    except httpx.TimeoutException as error:
        raise GeminiError("Gemini request timed out") from error
    except (httpx.HTTPError, ValueError) as error:
        raise GeminiError("Gemini request failed") from error

    text = _extract_text(data)
    if not text:
        raise GeminiError("Gemini returned no text")
    return text


def _audio_mime_type(file: UploadFile) -> str:
    content_type = (file.content_type or "").split(";", 1)[0].strip().lower()
    if content_type in _AUDIO_MIME_TYPES:
        return content_type

    filename = file.filename or ""
    if filename.lower().endswith(".m4a") and content_type in _M4A_FALLBACK_MIME_TYPES:
        return "audio/mp4"

    raise HTTPException(status_code=415, detail="Unsupported audio format")


def _transcription_prompt(locale: str | None) -> str:
    if locale is None:
        return _TRANSCRIPTION_PROMPT
    return (
        f"{_TRANSCRIPTION_PROMPT} The app locale is {locale}; use it only as a "
        "weak hint when the spoken language is ambiguous."
    )


async def transcribe(audio: bytes, mime_type: str, locale: str | None) -> str:
    if not GEMINI_API_KEY:
        raise GeminiError("GEMINI_API_KEY is not configured")
    if not MODEL_PATTERN.fullmatch(GEMINI_TRANSCRIPTION_MODEL):
        raise GeminiError("GEMINI_TRANSCRIPTION_MODEL contains invalid characters")

    url = (
        "https://generativelanguage.googleapis.com/v1beta/models/"
        f"{GEMINI_TRANSCRIPTION_MODEL}:generateContent"
    )
    payload = {
        "contents": [{
            "role": "user",
            "parts": [
                {"text": _transcription_prompt(locale)},
                {
                    "inline_data": {
                        "mime_type": mime_type,
                        "data": base64.b64encode(audio).decode("ascii"),
                    }
                },
            ],
        }],
        "generationConfig": {
            "maxOutputTokens": 4096,
            "temperature": 0,
        },
    }

    try:
        async with httpx.AsyncClient(timeout=60.0) as client:
            response = await client.post(
                url,
                headers={"x-goog-api-key": GEMINI_API_KEY},
                json=payload,
            )
            response.raise_for_status()
            data = response.json()
    except httpx.TimeoutException as error:
        raise GeminiError("Gemini transcription timed out") from error
    except (httpx.HTTPError, ValueError) as error:
        raise GeminiError("Gemini transcription failed") from error

    text = _extract_text(data)
    if not text:
        raise GeminiError("Gemini returned no transcript")
    return text


@router.post(
    "/twinkler/v1/complete",
    response_model=CompleteResponse,
    operation_id="twinkler_complete",
    tags=["Twinkler"],
    summary="Generate a Twinkler companion response",
    description=(
        "Sends the user message to the server-configured Gemini model. System "
        "instructions and the Gemini API key are never exposed to the client."
    ),
    responses={
        403: {"model": ErrorResponse, "description": "Invalid or missing API key"},
        429: {
            "model": ErrorResponse,
            "description": "Global or per-client request limit exceeded",
            "headers": {
                "Retry-After": {
                    "description": "Seconds until another request can be attempted",
                    "schema": {"type": "integer", "minimum": 1},
                }
            },
        },
        502: {"model": ErrorResponse, "description": "Gemini request failed"},
        503: {"model": ErrorResponse, "description": "Rate limiter unavailable"},
    },
)
async def twinkler_complete(
    request: CompleteRequest,
    http_request: Request,
    api_key: bool = RequireAPIKey,
) -> CompleteResponse:
    client_key = resolve_client_ip(http_request)
    await _enforce_rate_limit(client_key)
    try:
        text = await complete(request.user)
    except GeminiError as error:
        # Log the failure category, but never the prayer text or provider key.
        logger.warning("Twinkler AI request failed: %s", error)
        raise HTTPException(status_code=502, detail="AI service unavailable") from error
    return CompleteResponse(text=text)


@router.post(
    "/twinkler/v1/transcribe",
    response_model=CompleteResponse,
    operation_id="twinkler_transcribe",
    tags=["Twinkler"],
    summary="Transcribe a Twinkler voice recording",
    description=(
        "Transcribes an M4A recording in its original language. The optional "
        "locale is used only as a weak language hint."
    ),
    responses={
        403: {"model": ErrorResponse, "description": "Invalid or missing API key"},
        413: {"model": ErrorResponse, "description": "Audio file is too large"},
        415: {"model": ErrorResponse, "description": "Unsupported audio format"},
        429: {
            "model": ErrorResponse,
            "description": "Global or per-client request limit exceeded",
            "headers": {
                "Retry-After": {
                    "description": "Seconds until another request can be attempted",
                    "schema": {"type": "integer", "minimum": 1},
                }
            },
        },
        502: {"model": ErrorResponse, "description": "Gemini request failed"},
        503: {"model": ErrorResponse, "description": "Rate limiter unavailable"},
    },
)
async def twinkler_transcribe(
    http_request: Request,
    file: UploadFile = File(..., description="M4A voice recording"),
    locale: str | None = Form(
        default=None,
        max_length=35,
        description="Optional BCP 47 app locale used only as a weak hint",
    ),
    api_key: bool = RequireAPIKey,
) -> CompleteResponse:
    if locale is not None and not LOCALE_PATTERN.fullmatch(locale):
        raise HTTPException(status_code=422, detail="Invalid locale")

    try:
        mime_type = _audio_mime_type(file)
        audio = await file.read(_MAX_AUDIO_BYTES + 1)
    finally:
        await file.close()

    if not audio:
        raise HTTPException(status_code=422, detail="Audio file is empty")
    if len(audio) > _MAX_AUDIO_BYTES:
        raise HTTPException(status_code=413, detail="Audio file is too large")

    client_key = resolve_client_ip(http_request)
    await _enforce_rate_limit(client_key)

    try:
        text = await transcribe(audio, mime_type, locale)
    except GeminiError as error:
        # Keep this static: provider errors must never leak recording metadata.
        logger.warning("Twinkler transcription request failed")
        raise HTTPException(status_code=502, detail="AI service unavailable") from error
    return CompleteResponse(text=text)
